### ISSUE TITLE
Error fid = open(os fspath(file), "rb")] on python3.5.0

### ISSUE THREAD

**Issue by Gitllub** [textgain/grasp#7]
Hello  thank you for visitting my issue
I'm studying tensorflow by following "pygta5" on YouTube
I tried to run `[balance_data.py](https://github.com/Sentdex/pygta5/tree/master/Tutorial%20Codes/Part%208-13%20code)` file on both of "command prompt & IDLE"

### Error on command prompt :
Traceback (most recent call last):
  File "C:\Windows\System32\pygta5-master\Tutorial Codes\Part 8-13 code\balance_data.py", line 8, in <module>
    train_data = np.load('training_data.npy')
  File "C:\Users\decax64\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\lib\npyio.py", line 415, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'training_data.npy'

### Error on IDLE (only the last 3 lines) :
File "C:\Users\~\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 1062, in get_terminal_size
    size = os.get_terminal_size(sys.__stdout__.fileno())
AttributeError: 'NoneType' object has no attribute 'fileno'

I guess directory error
but doesnt work Even I copied training_data.npy file to /lib/ folder

Windows10
Python3.5.0
CPU:Xeon W3530 (similar to core i7 900)= neither AVX nor AVX2

The troublemaker file is : balance_data.py
My current step is :
https://www.youtube.com/watch?v=wIxUp-37jVY&list=PLQVvvaa0QuDeETZEOy4VdocT7TOjfSA8a&index=10

Regards...

**Comment by cite12345** [comment]
Please refer to this: https://bugs.python.org/issue24920
